### ISSUE TITLE
omp_lib.mod

### ISSUE THREAD

**Issue by YiZhiXiaoGuLI** [rballester/ttrecipes#1]
Pip install error:Fatal Error: Can't open module file 'omp_lib.mod' for reading at (1): No such file or directory

**Comment by rballester** [comment]
Did this happen using Windows? Unfortunately, the dependency ttpy is not supported in Windows as far as I know.

**Comment by YiZhiXiaoGuLI** [comment]
Yes,I did it on my Windows system.
OK,I will try linux next time. 
But I think it is great,maybe someday we can use it on Windows.

**Comment by YiZhiXiaoGuLI** [comment]
Linux：Run `sudo apt-get install gfortran` before `sudo pip install git+https://github.com/rballester/ttrecipes.git`

Successfully installed it!
